import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { gql } from "@apollo/client";
import client from "../../apollo-client";

// styles
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

//

export default function Home({ countries }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
        </div>

        <div className={styles.center}>
          <div className={styles.grid}>
            {countries.map((country) => (
              <a
                href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                className={styles.card}
                target="_blank"
                rel="noopener noreferrer"
              >
                <h2 className={inter.className}>
                  <span>{country.emoji}</span> {country.code}
                </h2>
                <p className={inter.className}>{country.name}</p>
              </a>
            ))}
          </div>
        </div>
        
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
  });
  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  };
}
